
add_executable(test2 test2.cpp)
# set_target_properties(test2 PROPERTIES EXCLUDE_FROM_ALL TRUE)
target_link_libraries(test2 allocators)

add_executable(test3 test3.cpp)
# set_target_properties(test3 PROPERTIES EXCLUDE_FROM_ALL TRUE)
target_link_libraries(test3 allocators)

add_executable(stats stats.cpp)
# set_target_properties(stats PROPERTIES EXCLUDE_FROM_ALL TRUE)
target_link_libraries(stats allocators)

add_executable(compilation_instantiation compilation_instantiation.cpp)
# set_target_properties(compilation_instantiation PROPERTIES EXCLUDE_FROM_ALL TRUE)
target_link_libraries(compilation_instantiation allocators)

add_executable(new_syntax new_syntax.cpp)
# set_target_properties(compilation_instantiation PROPERTIES EXCLUDE_FROM_ALL TRUE)
target_link_libraries(new_syntax allocators)

add_executable(buddy_allocator_algorithms_2 buddy_allocator_algorithms_2.cpp)
target_compile_features(buddy_allocator_algorithms_2 PRIVATE cxx_std_26)

add_executable(basic_buddy_allocator_test basic_buddy_allocator_test.cpp)
target_link_libraries(basic_buddy_allocator_test allocators)
# target_compile_features(basic_buddy_allocator_test PRIVATE cxx_std_26)

add_executable(any_block_allocator_test any_block_allocator_test.cpp)
target_link_libraries(any_block_allocator_test allocators)
# target_compile_features(any_block_allocator_test PRIVATE cxx_std_26)

add_executable(test_assert test_assert.cpp)
target_link_libraries(test_assert allocators)
target_compile_features(test_assert PRIVATE cxx_std_26)

add_executable(buddy_allocator_test_2 buddy_allocator_test_2.cpp)
target_link_libraries(buddy_allocator_test_2 allocators)
target_compile_features(buddy_allocator_test_2 PRIVATE cxx_std_26)

add_executable(buddy_internal_state_test buddy_internal_state_test.cpp)
target_link_libraries(buddy_internal_state_test allocators)
target_compile_features(buddy_internal_state_test PRIVATE cxx_std_26)

# add_executable(buddy_internal_state_test_2 buddy_internal_state_test_2.cpp)
# target_link_libraries(buddy_internal_state_test_2 allocators)
# target_compile_features(buddy_internal_state_test_2 PRIVATE cxx_std_26)
